=== IngyEl-Sakhawy/dealingWithXml/employeeschemadtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generated by XMLSpy v2024 (x64) (http://www.altova.com) -->
<!ELEMENT emp (name, phones, addresses, email)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (emgc | home | work) #REQUIRED >
<!ELEMENT phones (phone+)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT address (street, building_number, region, city, country)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT Employees (emp+)>
<!ATTLIST Employees
	xsi:noNamespaceSchemaLocation CDATA #FIXED "file:///E:/iti/xml/formInXml/employeeschema.xsd"
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>
<!ELEMENT addresses (address)>
<!ELEMENT building_number (#PCDATA)>

=== IngyEl-Sakhawy/dealingWithXml/generalData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Employees SYSTEM "E:\iti\xml\formInXml\employeeschemadtd.dtd">
<?xml-stylesheet type="text/css" href="style.css"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<emp>
		<name>john</name>
		<phones>
			<phone type="home">123-125-551</phone>
			<phone type="work">123-125-552</phone>
			<phone type="emgc">123-125-553</phone>
		</phones>
		<addresses>
			<address>
				<street>Main St</street>
				<building_number>1 no.</building_number>
				<region>Region</region>
				<city>City</city>
				<country>Country</country>
			</address>
		</addresses>
		<email>john@example.com</email>
	</emp>
	<emp>
		<name>louren</name>
		<phones>
			<phone type="home">123-125-551</phone>
			<phone type="work">123-125-552</phone>
			<phone type="emgc">123-125-553</phone>
		</phones>
		<addresses>
			<address>
				<street>Main St</street>
				<building_number>2 no.</building_number>
				<region>Region</region>
				<city>City</city>
				<country>Country</country>
			</address>
		</addresses>
		<email>louren@example.com</email>
	</emp>
	<emp>
		<name></name>
		<phones>
			<phone type="home">123-125-551</phone>
			<phone type="work">123-125-552</phone>
			<phone type="emgc">123-125-553</phone>
		</phones>
		<addresses>
			<address>
				<street>Main St</street>
				<building_number>2 no.</building_number>
				<region>Region</region>
				<city>City</city>
				<country>Country</country>
			</address>
		</addresses>
		<email>louren@example.com</email>
	</emp>
</Employees>
